config/routes.rb
Rails.application.routes.draw do

root "welcome#index"

    resources :users do
      member do
        get :following, :followers
      end
    end  

    resources :relationships, only: [:create, :destroy]
    resources :events do
      resources :comments

    end

  

  get '/login'     => 'sessions#new', as: :login
  post '/login'    => 'sessions#create', as: :log_cr
  delete '/logout' => 'sessions#destroy'

  get '/admin'     => 'sessions#admin'

  get '/comments' => 'comments#index'

  get 'eventusers/new' => 'eventusers#new'
  post 'eventusers/:event_id' => 'eventusers#create', as: :attend

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
    @comments = Comment.all
    
  end

  def show
    @event = Event.find(params[:event_id]) 
  end

  def new
    @comment = Comment.new
    @event = Event.find(params[:event_id]) 
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @user = current_user.id
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new(comment_params)
    @comment.user_id = @user

    if @comment.save
      redirect_to event_comments_path
      flash[:success] = "Your post has been sent"
      
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(event_params) 
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to events_path
  end

  private

  def comment_params
      params.require(:comment).permit(:title, :body)
  end

  def event_params
      params.require(:event).permit(:title, :description, :date, :start_time, :end_time, :location, :for_ages,)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_admin_comments.html.erb
<div class = "container">
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">All Comments</div>
<!-- Table -->
	<table class="table">
	  <thead>
	    <tr>
	        <th>Title</th>
	        <th>Body</th>
	        <th>User Id</th>
	        <th>Event Id</th>
	        <th>Action</th>
	    </tr>
	   </thead>   
	  
	  	<tbody>
	  		<% @comments.each do |comment| %>
	      <tr>
	        <td> <%= comment.title %> </td>
	        <td> <%= comment.body %> </td>
	        <td> <%= comment.user_id %> </td>
	        <td> <%= comment.event_id %> </td>
	        <td> <%#= link_to "More", event_comments_path %></td>
	        <td> <%#= link_to "Edit", event_comments_path %></td>
	        <td> <%#= link_to "Destroy", event_comments_path %></td>
	    	</tr>
			</tbody>	  
	  <% end %>
		
	  </table>

	</div>
</div>

app/views/comments/_editcomments.html.erb
<% if @comment.user==current_user %>

  <button type="button" class="btn btn-default btn-sm">
    <span class="glyphicon glyphicon-pencil"> 
      <%= link_to "Edit", edit_comment_path(@user) %>
    </span>
  </button>

  <button type="button" class="btn btn-default btn-sm">
    <span class="glyphicon glyphicon-trash">
      <%= link_to "Delete!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %> 
    </span>
  </button>

<% end %>

app/views/comments/_form_comment.html.erb
<div class="row text center">
  <div class="col-sm-6">
    <div class="thumbnail">
      <img src="http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons-256/3d-glossy-orange-orbs-icons-sports-hobbies/106502-3d-glossy-orange-orb-icon-sports-hobbies-party.png" alt="...">
      <div class="caption">
        <h3>Event</h3>
        <p> Name: <%=@event.title%> <br>
      Decription: <%=@event.description%> <br>

<h1>Submit your comment</h1>

<%= form_for [@event, @comment] do |f|%>

  <ul>
    <li><%= f.label :title %></li>
    <li><%= f.text_field :title %></li>
  </ul>

  <ul>
    <ul><%= f.label :body %></li>
    <ul><%= f.text_area :body %></li>
  </ul>

	<div>
    <ul><%= f.submit %></li>
  </div>
 
 <% end %> 

app/views/comments/index.html.erb
<div class = "container">
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">All Comments</div>
<!-- Table -->
	<table class="table">
	  <thead>
	    <tr>
	    	<th>Event Name</th>
	        <th>Title</th>
	        <th>Body</th>
	        <th>Submitted by</th>
	        <th>Link to event</th>

	    </tr>
	   </thead>   
	  
	  	<tbody>
	  		<% @comments.each do |comment| %>
	      <tr>
	      	<td> <%= comment.event.title %> </td>
	        <td> <%= comment.title %> </td>
	        <td> <%= comment.body %> </td>
	        <td> <%= comment.user_id %> </td>
	        <td> <%= link_to "Get More", events_path %> </td>
	        <td> <%#= link_to "Edit", event_comments_path %></td>
	        <td> <%#= link_to "Destroy", event_comments_path %></td>
	    	</tr>
			</tbody>	  
	  <% end %>
		
	  </table>

	</div>
</div>

app/views/comments/new.html.erb
<section class = "comment">
  <div class = "container">
    <div class="row">
      <div class="col-sm-12 text-center">
          <%= render "comments/form_comment" %>
      </div>
    </div>
  </div>
</section>

app/views/comments/show.html.erb
<h1>These are the comments for event <%= @event.title %> </h1>

<%= @event.comments %>