config/routes.rb
Rails.application.routes.draw do

root "welcome#index"

    resources :users do
      member do
        get :following, :followers
      end
    end  

    resources :relationships, only: [:create, :destroy]
    resources :events do
      resources :comments

    end

  

  get '/login'     => 'sessions#new', as: :login
  post '/login'    => 'sessions#create', as: :log_cr
  delete '/logout' => 'sessions#destroy'

  get '/admin'     => 'sessions#admin'

  get '/comments' => 'comments#index'

  get 'eventusers/new' => 'eventusers#new'
  post 'eventusers/:event_id' => 'eventusers#create', as: :attend

 

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	
	has_secure_password
	
  has_many :eventusers
  has_many :events, through: :eventusers
	has_many :comments


	has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
	                                   foreign_key: "followed_id",
	                                   dependent:   :destroy
	has_many :following, through: :active_relationships,  source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

  

 # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.delete(followed_id: other_user.id)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Event.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :current_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

	def index
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @user_events = @user.events
    @feed = feed
    @owned_events = Event.where(user_id: @user.id)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	session[:user_id] = @user.id.to_s
      redirect_to users_path
      
    else
      render :new
    end
  end

  def edit
  	@user = User.find(params[:id])
  end
  
  def destroy
	  @user = User.find(params[:id])
	  @user.destroy
	  redirect_to users_path
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)	
	    redirect_to users_path
	  else
	    render :edit
	  end
	end
  def feed
    @event  = current_user.events.build
    @feed_items = current_user.feed
  end
  

  private

	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :user_name, :bio, :image, :email, :password, :password_confirmation)
	  end
    
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_admin_users.html.erb
<div class = "container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">All Users</div>
    
    <!-- Table -->
    <table class="table-condensed">

    	<thead>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Username</th>
          <th>Email</th>
          <th>Action</th>
        </tr>

     	</thead>
      
      <% @users.each do |user| %>
      
      <tbody>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.user_name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "More", user_path(user) %>
      	<%= link_to "Edit", edit_user_path(user) %>
      	<%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %></td>
        </tr>
      </tbody>
    
      <% end %>
    
    </table>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != user %>
  <div id="follow_form">
  <% if current_user.following.include?(user) %>
    <%= render :partial => 'unfollow', :locals => { user: user } %>   
  <% else %>
    <%= render :partial => 'follow', :locals => { user: user } %>
  <% end %>
  <br>
  </div>
<% end %>

app/views/users/_loggedin_show.html.erb
<div class = "container">
  <div class = "title">
    <h1> My Profile </h1>
    <%= render 'sessions/stats' %>
    <div class="row text-center">
	    <div class="col-sm-3">
	      <div class="thumbnail">
	        <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" alt="...">
	        <div class="caption text-center">
	          <ul>
	            <li><strong> Name: </strong> <%=@user.first_name%></li>
	            <li><strong> Email: </strong> <%=@user.email%></li>
	            <li><strong> About me: </strong> <%=@user.bio%><li/>
	          <br>
	          </ul>  
						<button type="button" class="btn btn-default btn-sm">
						  <span class="glyphicon glyphicon-pencil"> 
						    <%= link_to "Edit", edit_user_path(@user) %>
						  </span>
						</butto
						<button type="button" class="btn btn-default btn-sm">
						  <span class="glyphicon glyphicon-trash">
						    <%= link_to "Delete!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %> 
						  </span>
						</button>
	        </div>
      </div>
    </div>
  </div>
</div>

        

app/views/users/_loggedoutuser_show.html.erb
<div class = "container">
  <div class = "title">
    <h1> This is the profile for <%= @user.user_name %> </h1>
  <section class="stats">
      <%= render 'sessions/stats' %>
    </section>
  <div class="row text-center">
    <div class="col-sm-3">
      <div class="thumbnail">
        <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" alt="...">
        <div class="caption text-center">
          <ul>
            <li><strong> Name: </strong> <%=@user.first_name%></li>
            <li><strong> Email: </strong> <%=@user.email%></li>
            <li><strong> About me: </strong> <%=@user.bio%><li/>
          <br>
          </ul>
        </div>
      </div>
    </div>
  </div>
          

app/views/users/_notusershow.html.erb
  <section class="eventTable">
    <h2>Hi<%=current_user.user_name%> you are looking at the profile page for: </h2>
    <div class="container">
      <div class="row">
        <div class = "title text-center" >
            <div class = "col-sm-3">
              <div class="list-group">
                <a href="#" class="list-group-item active">
                 <%= @user.first_name%> <%= @user.last_name%> 
                </a>
                <a href="#" class="list-group-item"><%= image_tag @user.image.url(:small) %></a>
                <a href="#" class="list-group-item"><%= @user.bio %></a>
                <a href="#" class="list-group-item"><%= @user.email %></a>             
              </div>
            </div>
        </div>  
      </div>
      <%= render 'sessions/stats' %>

      <%= render 'follow_form' %>
      <br>
      <div class="btn-group">
      <button type="button" class="btn btn-alert"><%= link_to "Add an event", new_event_path %> </button>  
      </div>
    </div>
 
</section>

app/views/users/_unfollow.html.erb
	<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
	             html: { method: :delete },
	             ) do |f| %>
	  <%= f.submit "Unfollow", class: "btn" %>
	<% end %>

app/views/users/_useredit.html.erb
<% if @user==current_user %>

  <button type="button" class="btn btn-default btn-sm">
    <span class="glyphicon glyphicon-pencil"> 
      <%= link_to "Edit", edit_user_path(@user) %>
    </span>
  </button>

  <button type="button" class="btn btn-default btn-sm">
    <span class="glyphicon glyphicon-trash">
      <%= link_to "Delete!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %> 
    </span>
  </button>

<% end %>

app/views/users/edit.html.erb
<h1> Edit your profile! </h1>

<%= form_for @user do |f| %>

	<div class="field">
	  <%= f.label :first_name %><br>
	  <%= f.text_field :first_name %>
	</div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>

  <div class="picture">
  	<%= f.label :pic %>
    <%= f.file_field :pic %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

	<div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  
  <div class ="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

app/views/users/index.html.erb
<h2> 
    Hi <%=current_user.user_name%> check out all the users on our network 
  </h2>

<div class ="container">
  <% @users.each do |u| %>  
    <div class="row">
      <div class="title">
        <div class="col-sm-3">
          <div class="thumbnail">
            <%= image_tag u.image.url(:small) %>
            <div class="caption text center">
              <ul>
                <li class = "a">Name: <%= u.first_name %> <%= u.last_name %></li>
                <li>Email: <%= u.email %></li>
                <li><%= u.bio %></li>
                <li> Latest event: <%= u.events.last %></li>
                <li><%= link_to "More", user_path(u)%></li>
              </ul>
              <%= render :partial => 'follow_form', :locals => { user: u } %>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/users/new.html.erb
<div class = "container">
  <%= form_for @user do |f| %>
  <div class="maincontainer" id="signup">
    <h1>Sign Up</h1> 
        <p>We can't wait to hear from you</p>
    
    <ul>
      <li><%= f.label :first_name %></li>
      <li><%= f.text_field :first_name %></li>
    </ul>
    <ul>
      <li><%= f.label :last_name %></li>
      <li><%= f.text_field :last_name %></li>
    </ul>
    <ul>
      <li><%= f.label :user_name %></li>
      <li><%= f.text_field :user_name %></li>
    </ul>
    <ul>
      <li><%= f.label :bio %></li>
      <li><%= f.text_field :bio %></li>
    </ul>
    <ul>
      <li><%= f.label :image %></li>
      <li><%= f.file_field :image %></li>
    </ul>
    <ul>
      <li><%= f.label :email %></li>
      <li><%= f.text_field :email %></li>
    </ul>
    <ul>
      <li><%= f.label :password %></li>
      <li><%= f.password_field :password %></li>
    </ul>
    <ul>
      <li><%= f.label :password_confirmation %></li>
      <li><%= f.password_field :password_confirmation %></li>
    </ul>
    <ul>
      <li><%= f.submit %></li>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
  
<section class="eventTable">
  <div class ="container">
    <div class = "header col-sm-12 "> 
      <% if @user == current_user %>
        <h2>Hi <%=current_user.user_name%> here's your profile</h2>
      <% else %>
        <h2>Hi <%=current_user.user_name%> this is the profile page you requested</h2>
      <%end%>
    </div>
  </div>

  <div class ="container">
      <div class="row">
        <div class = "title text-center">
          <div class = "col-sm-3">
            <div class="list-group">
              <a href="#" class="list-group-item active">
               <%= @user.first_name%> <%= @user.last_name%> </a>
              <a href="#" class="list-group-item">
                <%= image_tag @user.image.url(:small) %>
                <br>
                <br>
                <ul>
                  <li><%= @user.bio %></li>
               
                  <li>Email me: <%=@user.email %></li>
                </ul>
              </a>            
            </div>
                My connections <%= render 'sessions/stats' %>
                <br>
                <%= render :partial => 'follow_form', :locals => { user: @user } %>
            
            <div class="list-group"> 
              <% if @user == current_user %>
                <%= render 'useredit' %>
              <% end %>
            </div>
          </div>
        </div>
    
        <div class = "title text-left">
          <div class = "col-sm-3">
            <div class="list-group">
              <a href="#" class="list-group-item active">
               Events followed by <%= @user.first_name%> <%= @user.last_name%> </a>
              <a href="#" class="list-group-item"><%= render 'sessions/feed' %></a>
            </div>
          </div>
        </div>

        <div class = "title text-left">
          <div class = "col-sm-3">
            <div class="list-group">
              <a href="#" class="list-group-item active">
               Events owned by <%= @user.first_name%> <%= @user.last_name%> </a>
              <a href="#" class="list-group-item"><%= render 'sessions/owned' %></a>
            </div>
          </div>
        </div>

        <div class = "title text-left">
          <div class = "col-sm-3">
            <div class="list-group">
              <a href="#" class="list-group-item active">
               Comments owned by <%= @user.first_name%> <%= @user.last_name%> </a>
              <a href="#" class="list-group-item"><%= render 'sessions/owned' %></a>
            </div>
          </div>
        </div>

      </div>
  

  <div class="panel panel-default">
    <div class="panel-heading text-center"><%= link_to "Make more connections!", users_path %> </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class = "container">
<% provide(:title, @title) %>
	<div class="row">
	  <aside class="col-md-4">
	    <section class="user_info">
	      <h1><%= @user.user_name %></h1>
	    </section> 
	    <section class="stats">
	      <%= render 'sessions/stats' %>
	      <% if @users.any? %>
	        <div class="user_avatars">
	          <% @users.each do |user| %>
	          <ul>
	            <li> <%= user.user_name %> </li>
	          <% end %>
	          </ul>
	        </div>
	      <% end %>
		</section>
	</aside>
		
</div>	
	  