config/routes.rb
Rails.application.routes.draw do

root "welcome#index"

    resources :users do
      member do
        get :following, :followers
      end
    end  

    resources :relationships, only: [:create, :destroy]
    resources :events do
      resources :comments

    end

  

  get '/login'     => 'sessions#new', as: :login
  post '/login'    => 'sessions#create', as: :log_cr
  delete '/logout' => 'sessions#destroy'

  get '/admin'     => 'sessions#admin'

  get '/comments' => 'comments#index'

  get 'eventusers/new' => 'eventusers#new'
  post 'eventusers/:event_id' => 'eventusers#create', as: :attend

 

end

app/models/event.rb
class Event < ActiveRecord::Base
	
	has_many :eventusers
	has_many :users, through: :eventusers
	has_many :comments
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
    @events = Event.all
  end

  def show
  	@event = Event.find(params[:id]) 
    @user = User.find_by_id(@event.user_id)

  end

  def new
    @event = Event.new
  end

  def create
    
    @event = Event.new(event_params)
    
   
    if @event.save
      current_user.events<<@event
     
      redirect_to user_path(current_user)
      
    else
      render :new
    end
  end

	def edit
	  @event = Event.find(params[:id])
	end

  def update
		@event = Event.find(params[:id])

		if @event.update_attributes(event_params)	
	    redirect_to user_path
	  else
	    render :edit
	  end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

private

	def event_params
	    params.require(:event).permit(:title, :description, :date, :start_time, :end_time, :location, :for_ages, :event_id, :user_id)
	end

  def comment_params
      params.require(:comment).permit(:title, :body)
  end
end

app/helpers/events_helper.rb
module EventsHelper


end

app/views/events/_events_index.html.erb
<section class="eventTable">
	<div class="container">
		<div class="row">
			<div class = "title text-center" >
				<h2> 
					Hi <%=current_user.user_name%> check out events from our network 
				</h2>
				<% @events.each do |e| %>
					<div class = "col-sm-3">
						<div class="list-group">
						  <a href="#" class="list-group-item active">
						    <%= e.title %>
						  </a>
						  <a href="#" class="list-group-item"><%= e.description %></a>
						  <a href="#" class="list-group-item"><%= e.date.strftime("%v") %></a>
						  <a href="#" class="list-group-item"><%= e.start_time.strftime("%r")  %></a>
						  <a href="#" class="list-group-item"><%= e.location %></a>
						   <button type="button" class="btn btn-alert"><%= link_to "More details", event_path(e) %> </button>
						</div>
					</div>
				<%end%>
			</div>	
		</div>
	</div>
</section>
	

		
		
		

app/views/events/_form_addevent.html.erb
<%= form_for @event do |f| %>

  <ul>
    <li><%= f.label :title %>
    <li><%= f.text_field :title %>
  </ul>

  <ul>
    <li><%= f.label :description %>
    <li><%= f.text_area :description %>
  </ul>

  <ul>
    <li><%= f.label :date %></li>
    <li><%= f.date_field :date %></li>
  </ul>

  <ul>
    <li><%= f.label :start_time %></li>
    <li><%= f.datetime_field :start_time %></li>
  </ul>

  <ul>
    <li><%= f.label :end_time %></li>
    <li><%= f.datetime_field :end_time %></li>
  </ul>

  <ul>
    <li><%= f.label :location %></li>
    <li><%= f.text_field :location %></li>
  </ul>

  <ul>
    <li><%= f.label :for_ages %></li>
      <%= f.select :for_ages, options_for_select([["For Ages", ""], "Tinnies", "Toddler", "Teens"]) %>
    </li>
  </ul>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <ul>
    <li><%= f.submit %></li>
  </ul>

<% end %>

app/views/events/edit.html.erb
  <%if @event.user_id == current_user.id %>
    
    <%= form_for @event do |f| %>

      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>

      <div>
        <%= f.label :date %>
        <%= f.date_field :date %>
      </div>

      <div>
        <%= f.label :start_time %>
        <%= f.datetime_field :start_time %>
      </div>

      <div>
        <%= f.label :end_time %>
        <%= f.datetime_field :end_time %>
      </div>

      <div>
        <%= f.label :location %>
        <%= f.text_field :location %>
      </div>

      <div>
        <%= f.label :for_ages %>
        <%= f.text_field :for_ages %>
      </div>
      
      <div>
        <%= f.submit %>
      </div>
      
  <%end%>

  <% else %>

  <h1> Sorry you don't have persmission to edit </h1>

  <%end%>

app/views/events/index.html.erb
<%= render :partial => 'events_index', :locals => { event: @event} %>

app/views/events/new.html.erb
<section class = "login">
  <div class = "container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h1> Add an event</h1>
        <%= render "events/form_addevent" %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
  <section class="eventTable">
    <h2>Hi <%=current_user.user_name%> here are the details about the event your requested </h2>
    <div class="container">
      <div class="row">
        <div class = "title text-center" >
          <div class = "col-sm-4">
            <div class="list-group">
              <a href="#" class="list-group-item active">
               <%=@event.title%> 
               <br> Submitted by: <%=@user.user_name%> 
              </a>
              <a href="#" class="list-group-item">
               <%=@event.description%> 
              </a>
              <a href="#" class="list-group-item">
               Would be good for <%=@event.for_ages%>'s
              </a>
              <a href="#" class="list-group-item">
                Happening on <%=@event.date.strftime("%v")%> 
              </a>
              <a href="#" class="list-group-item">
                From <%=@event.start_time.strftime("%l")%> until <%=@event.end_time.strftime("%r") %> 
              </a>
              <a href="#" class="list-group-item">
               At this location <%=@event.location%> 
              </a>
            </div>

            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-pencil"> 
                <%= link_to "Edit", edit_event_path(@event) %>
              </span>
            </button>

            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-trash">
                <%= link_to "Delete!", edit_event_path, method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %> 
              </span>
            </button>

            <br>


            <span class="label"> <%= link_to "Add Comment", new_event_comment_path(@event)%></span>
            <% if !(current_user.events.exists?(@event)) %>
            <span class="label"> <%= link_to 'Attend', attend_path(@event), method: :post %></span>
            <% end %>
          </div>
          <div class="col-sm-8">
          <% @event.users.each do |e| %>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </a>
              </div>
              <div class="media-body text-left">
                <h4 class="media-heading ">Attending</h4>
                <%= e.user_name %>
                <%= link_to "More details", user_path(@user)%>

              </div>
            </div>
          <% end %>
          <% @event.comments.each do |c|%>
          <div class="media text-left">
            <div class="media-left ">
              <a href="#">
                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">Comment from <%= c.user.user_name %> </h4>
                <%= c.title %>
                <%= c.body %>
                <%= link_to "See all comments", comments_path%>
            </div>

             

            </div>
          <% end %>
        </div>
        </div>  
      </div>
    </div>
  </section>


  