config/routes.rb
Rails.application.routes.draw do

root "welcome#index"

    resources :users do
      member do
        get :following, :followers
      end
    end  

    resources :relationships, only: [:create, :destroy]
    resources :events do
      resources :comments

    end

  

  get '/login'     => 'sessions#new', as: :login
  post '/login'    => 'sessions#create', as: :log_cr
  delete '/logout' => 'sessions#destroy'

  get '/admin'     => 'sessions#admin'

  get '/comments' => 'comments#index'

  get 'eventusers/new' => 'eventusers#new'
  post 'eventusers/:event_id' => 'eventusers#create', as: :attend

 

end

app/models/attend.rb
class Attend < ActiveRecord::Base
	belongs_to :attend, class_name: "Event"
  belongs_to :attending, class_name: "Event"
  validates :attend_id, presence: true
  validates :attending_id, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	
	has_many :eventusers
	has_many :users, through: :eventusers
	has_many :comments
end

app/models/eventuser.rb
class Eventuser < ActiveRecord::Base
  belongs_to :event 
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  	belongs_to :followed, class_name: "User"
  	validates :follower_id, presence: true
  	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	
	has_secure_password
	
  has_many :eventusers
  has_many :events, through: :eventusers
	has_many :comments


	has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
	                                   foreign_key: "followed_id",
	                                   dependent:   :destroy
	has_many :following, through: :active_relationships,  source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

  

 # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.delete(followed_id: other_user.id)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Event.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
    @comments = Comment.all
    
  end

  def show
    @event = Event.find(params[:event_id]) 
  end

  def new
    @comment = Comment.new
    @event = Event.find(params[:event_id]) 
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @user = current_user.id
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new(comment_params)
    @comment.user_id = @user

    if @comment.save
      redirect_to event_comments_path
      flash[:success] = "Your post has been sent"
      
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(event_params) 
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to events_path
  end

  private

  def comment_params
      params.require(:comment).permit(:title, :body)
  end

  def event_params
      params.require(:event).permit(:title, :description, :date, :start_time, :end_time, :location, :for_ages,)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
    @events = Event.all
  end

  def show
  	@event = Event.find(params[:id]) 
    @user = User.find_by_id(@event.user_id)

  end

  def new
    @event = Event.new
  end

  def create
    
    @event = Event.new(event_params)
    
   
    if @event.save
      current_user.events<<@event
     
      redirect_to user_path(current_user)
      
    else
      render :new
    end
  end

	def edit
	  @event = Event.find(params[:id])
	end

  def update
		@event = Event.find(params[:id])

		if @event.update_attributes(event_params)	
	    redirect_to user_path
	  else
	    render :edit
	  end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

private

	def event_params
	    params.require(:event).permit(:title, :description, :date, :start_time, :end_time, :location, :for_ages, :event_id, :user_id)
	end

  def comment_params
      params.require(:comment).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	

  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id.to_s
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
  	session.delete(:user_id)
    redirect_to login_path
  end

  def home
    if current_user
      @event  = current_user.events.build
      @feed_items = current_user.feed
      
    end
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :current_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

	def index
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @user_events = @user.events
    @feed = feed
    @owned_events = Event.where(user_id: @user.id)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	session[:user_id] = @user.id.to_s
      redirect_to users_path
      
    else
      render :new
    end
  end

  def edit
  	@user = User.find(params[:id])
  end
  
  def destroy
	  @user = User.find(params[:id])
	  @user.destroy
	  redirect_to users_path
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)	
	    redirect_to users_path
	  else
	    render :edit
	  end
	end
  def feed
    @event  = current_user.events.build
    @feed_items = current_user.feed
  end
  

  private

	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :user_name, :bio, :image, :email, :password, :password_confirmation)
	  end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



  def index
    @events = Event.all
  end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper


end

app/helpers/eventsuser_helper.rb
module EventsuserHelper
end

app/helpers/eventusers_helper.rb
module EventusersHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clairesconnections</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Claire's Connections</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <% if current_user %>
          <a class= <%= link_to 'My Profile', user_path(current_user) %> </a></li>
          <% else current_user %>
          <a class= <%= link_to 'My Profile', users_path %> </a></li>
          <% end %>
        <li class="active">
        <a class= <%= link_to 'Comments', comments_path %> </a></li>
        <li>
          <a href="/events/new">Add an Event</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Events 
            <span class="caret"></span>
            </a>
          <ul class="dropdown-menu">
            <li><a class = <%= link_to 'All Events', events_path %></a></li>
            <li><a href="#">My Events</a></li>
            <li><a href="#">Events by date</a></li>
            <li role="separator" class="divider"></li>
            <li><a class = <%= link_to 'All Comments', comments_path %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Likes</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li> 
          <% if current_user %>
              Hi <%= current_user.first_name %> 
          <% else %>
            <%= link_to 'Log In', login_path %> 
        </li>
          <% end %> 
          
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <li><%= link_to 'Sign Up', new_user_path %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

<br>
<br>

</body>

</html>